(function(){
  var o=window.fetch;
  function deepClone(x){try{return JSON.parse(JSON.stringify(x));}catch(e){return x;}}
  var fallbacks={
    domainInfo:{list:[],config:[{tenantId:0,currency:"BRL",symbol:"R$"},{tenantId:1,currency:"BRL",symbol:"R$"}],domains:[],tenantId:1,currency:"BRL",symbol:"R$"},
    channelInfo:{id:1,tenantId:1,domain:"localhost:3000",currency:"BRL",symbol:"R$",config:[{tenantId:1,currency:"BRL",symbol:"R$"}]},
    tenantInfo:{tenantId:1,currency:"BRL",symbol:"R$",id:1,region:{currency:"BRL",symbol:"R$",language:"pt-BR"},currencySymbol:"R$",siteName:"A73",appIcon:"/s5/app-icon/1222508/LOGO.jpg",siteLogo:"/s5/app-icon/1222508/LOGO.jpg",appLanguage:["pt-BR","en","es"],appDefaultLanguage:"pt-BR"},
    authTenants:[{id:1,tenantId:1,currency:"BRL",symbol:"R$",name:"A73"}],
    homeList:{list:[{games:[],items:[]}],total:0},
    homeHot:{list:[{games:[],items:[]}],total:0},
    homePopularGames:{list:[{games:[],items:[]}],games:[],total:0},
    homeMarquee:{content:[],list:[],value:[]},
    marqueeList:{content:[],list:[],value:[]},
    homeCarousel:{content:[],list:[],value:[]},
    carouselConfigList:{content:[],list:[],value:[]},
    bannerList:{list:[],total:0},
    mainMediaList:{list:[],total:0},
    activityListPublic:{list:[],total:0},
    bannerQuickEntryListPublic:{list:[],total:0},
    tenantFooterText:{text:"",content:[]},
    announcementLoginOut:{list:[],value:[]}
  };
  function decryptMl(t){if(!t||typeof t!=="string")return t;try{var s=decodeURIComponent(atob(t.split("").reverse().join("")));return JSON.parse(s);}catch(e){return null;}}
  function ensureCurrency(o){if(!o||typeof o!=="object")return o;if(!o.currency){o.currency="BRL";o.symbol="R$";}if(!o.region){o.region={currency:"BRL",symbol:"R$",language:"pt-BR"};}else{if(!o.region.currency){o.region.currency="BRL";o.region.symbol="R$";}if(!o.region.language){o.region.language="pt-BR";}}if(!o.appLanguage||!Array.isArray(o.appLanguage)){o.appLanguage=["pt-BR","en","es"];}if(!o.appDefaultLanguage){o.appDefaultLanguage="pt-BR";}if(!Array.isArray(o.list)){o.list=[];}if(typeof o.total!=="number"){o.total=0;}if(Array.isArray(o.config)&&o.config.length){o.config.forEach(ensureCurrency);}return o;}
  function ensureListItems(o){if(!o||!o.list)return;if(!Array.isArray(o.list))o.list=[];o.list.forEach(function(item){if(item&&typeof item==="object"){if(!Array.isArray(item.games))item.games=[];if(!Array.isArray(item.items))item.items=[];if("content"in item&&!Array.isArray(item.content))item.content=[];}});}
  function ensureContentEverywhere(o){if(!o||typeof o!=="object")return;if("content"in o&&!Array.isArray(o.content))o.content=[];if("value"in o&&!Array.isArray(o.value))o.value=[];if(Array.isArray(o.list))o.list.forEach(ensureContentEverywhere);if(Array.isArray(o.games))o.games.forEach(ensureContentEverywhere);}
  function fixItem(r,proc){if(!r||!r.result)return;if(!r.result.data)r.result.data={};var j=r.result.data.json;if(j===undefined&&r.result.data&&typeof r.result.data==="object"&&!Array.isArray(r.result.data)&&!("json"in r.result.data)){j=r.result.data;r.result.data={json:j};}var fb=getFallback(proc);if(typeof j==="string"){var d=decryptMl(j);j=(d&&typeof d==="object")?d:fb;}if(!j||typeof j!=="object"){j=fb;}if(Array.isArray(j)){j={list:j,total:j.length};}if(j&&typeof j==="object"){ensureCurrency(j);if(!Array.isArray(j.list))j.list=[];if(typeof j.total!=="number")j.total=0;ensureListItems(j);if(!Array.isArray(j.games))j.games=[];if(!Array.isArray(j.content))j.content=[];if(!Array.isArray(j.value))j.value=[];ensureContentEverywhere(j);safeShape(j);}r.result.data.json=j;}
  function getProcsFromUrl(url){var procs=[];try{var m=(url||"").match(/trpc\/([^?&#]+)/);if(m)procs=m[1].split(",").map(function(p){var x=p.trim().split(".");return x[0]+(x[1]?x[1].charAt(0).toUpperCase()+x[1].slice(1):"");});}catch(e){}if(!procs.length){var u=url||"";if(u.indexOf("tenant")>=0&&u.indexOf("domain")>=0)procs=["domainInfo"];else if(u.indexOf("tenant")>=0)procs=["tenantInfo"];else if(u.indexOf("domain")>=0)procs=["domainInfo"];else if(u.indexOf("popular")>=0)procs=["homePopularGames"];else if(u.indexOf("carouselConfig")>=0)procs=["carouselConfigList"];else if(u.indexOf("marquee")>=0||u.indexOf("carousel")>=0)procs=["homeMarquee"];else if(u.indexOf("banner")>=0&&u.indexOf("quickEntry")>=0)procs=["bannerQuickEntryListPublic"];else if(u.indexOf("banner")>=0)procs=["bannerList"];else if(u.indexOf("mainMedia")>=0)procs=["mainMediaList"];else if(u.indexOf("activity")>=0)procs=["activityListPublic"];else if(u.indexOf("footerText")>=0)procs=["tenantFooterText"];else if(u.indexOf("announcement")>=0&&(u.indexOf("loginout")>=0||u.indexOf("loginOut")>=0))procs=["announcementLoginOut"];else if(u.indexOf("announcement")>=0)procs=["announcementLoginOut"];else if(u.indexOf("home.hot")>=0)procs=["homeHot"];else if(u.indexOf("home.list")>=0||(u.indexOf("home")>=0&&u.indexOf("list")>=0))procs=["homeList"];else if(u.indexOf("home")>=0)procs=["homeList"];else procs=["homeList"];}return procs;}
  var universalSafe={list:[{games:[],items:[],content:[],value:[]}],games:[],content:[],value:[],total:0};
  function fixTrpcJson(data,url){if(!data)return data;var procs=getProcsFromUrl(url);if(Array.isArray(data)){data.forEach(function(r,i){if(!r||!r.result){var p=procs[i]||procs[0]||"homeList";data[i]={result:{data:{json:deepClone(universalSafe),meta:{}}}};}if(data[i]&&data[i].result&&data[i].result.data){var q=procs[i]||procs[0]||"homeList";fixItem(data[i],q);}});return data;}fixItem(data,procs[0]||"homeList");return data;}
  function getFallback(proc){var u=proc?proc.toLowerCase():"";var fb;if(u.indexOf("domain")>=0&&u.indexOf("tenant")>=0)fb=fallbacks.domainInfo;else if(u.indexOf("channel")>=0)fb=fallbacks.channelInfo;else if(u.indexOf("tenant")>=0&&u.indexOf("info")>=0)fb=fallbacks.tenantInfo;else if(u.indexOf("carouselconfig")>=0)fb=fallbacks.carouselConfigList;else if(u.indexOf("popular")>=0)fb=fallbacks.homePopularGames;else if(u.indexOf("marquee")>=0||u.indexOf("carousel")>=0)fb=fallbacks.homeMarquee;else if(u.indexOf("banner")>=0&&u.indexOf("quick")>=0)fb=fallbacks.bannerQuickEntryListPublic;else if(u.indexOf("banner")>=0)fb=fallbacks.bannerList;else if(u.indexOf("mainmedia")>=0)fb=fallbacks.mainMediaList;else if(u.indexOf("activity")>=0)fb=fallbacks.activityListPublic;else if(u.indexOf("footer")>=0)fb=fallbacks.tenantFooterText;else if(u.indexOf("announcement")>=0)fb=fallbacks.announcementLoginOut;else if(u.indexOf("hot")>=0)fb=fallbacks.homeHot;else fb=fallbacks[proc]||fallbacks.homeList;return deepClone(fb);}
  function mockTrpcResponse(url){var procs=getProcsFromUrl(url);if(!procs.length){var u=url||"";if(u.indexOf("tenant")>=0)procs=["tenantInfo"];else if(u.indexOf("domain")>=0)procs=["domainInfo"];else procs=["homeList"];}var arr=[];for(var i=0;i<procs.length;i++){var fb=getFallback(procs[i]);arr.push({result:{data:{json:fb,meta:{}}}});}var body=arr.length>1?arr:arr[0];return new Response(JSON.stringify(body),{status:200,headers:{"Content-Type":"application/json"}});}
  function safeShape(o){if(!o||typeof o!=="object")return;if(!Array.isArray(o.list))o.list=[];if(!Array.isArray(o.games))o.games=[];if(!Array.isArray(o.content))o.content=[];if(!Array.isArray(o.value))o.value=[];if(!Array.isArray(o.segments))o.segments=o.list||[];if(typeof o.total!=="number")o.total=0;ensureListItems(o);ensureContentEverywhere(o);}
  function isApiOrTrpc(s){return s&&(s.indexOf("/api/")>=0||s.indexOf("trpc")>=0||s.indexOf("frontend")>=0||s.indexOf("home.")>=0);}
  function isValidTrpc(j){if(!j)return false;if(Array.isArray(j))return j.some(function(x){return x&&x.result;});return !!(j.result&&j.result.data);}
  function handleFetchResponse(r,s){if(!isApiOrTrpc(s))return r;if(!r.ok)return mockTrpcResponse(s);return r.clone().text().then(function(t){var j;try{j=t?JSON.parse(t):null;}catch(e){return mockTrpcResponse(s);}if(!j)return mockTrpcResponse(s);if(!isValidTrpc(j))return mockTrpcResponse(s);try{var fixed=fixTrpcJson(j,s);return new Response(JSON.stringify(fixed),{status:200,headers:{"Content-Type":"application/json"}});}catch(e){return mockTrpcResponse(s);}}).catch(function(){return mockTrpcResponse(s);});}
  function patchedFetch(u,op){var s=typeof u==="string"?u:(u&&(u.url||u.toString&&u.toString())||"");if(s&&(s.indexOf("api5.")>=0||s.indexOf("a-b-c-8.com")>=0)){try{var p=new URL(s,"http://x");u=location.origin+p.pathname+p.search;}catch(e){}}return o.apply(this,arguments).then(function(r){return handleFetchResponse(r,s);});}
  window.fetch=patchedFetch;
  if(typeof globalThis!=="undefined")globalThis.fetch=patchedFetch;
  document.addEventListener("DOMContentLoaded",function(){window.fetch=patchedFetch;if(typeof globalThis!=="undefined")globalThis.fetch=patchedFetch;});
})();
